services:
  mysql:
    image: mysql:8.0
    container_name: lf-alixpress-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: aliexpress
      MYSQL_USER: aliexpress
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

